"""empty message

Revision ID: 10ca724442c0
Revises: 33001410a8fb
Create Date: 2024-03-01 16:05:10.073964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ca724442c0'
down_revision = '33001410a8fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pinned', schema=None) as batch_op:
        batch_op.alter_column('article_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pinned', schema=None) as batch_op:
        batch_op.alter_column('article_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
