"""empty message

Revision ID: 33001410a8fb
Revises: 28ccb38b118d
Create Date: 2024-03-01 12:36:02.201484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33001410a8fb'
down_revision = '28ccb38b118d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pinned',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_watchlist')
    op.drop_table('user_pinned')
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_close', sa.Float(), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('market_cap',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('pe_ratio',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('sector',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.alter_column('sector',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('pe_ratio',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('market_cap',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('previous_close')

    op.create_table('user_pinned',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('article_id', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'article_id')
    )
    op.create_table('user_watchlist',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('stock_id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'stock_id')
    )
    op.drop_table('watchlist')
    op.drop_table('pinned')
    # ### end Alembic commands ###
