"""added stock column

Revision ID: 94e9dd5ba749
Revises: 28ccb38b118d
Create Date: 2024-02-29 14:41:58.839274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94e9dd5ba749'
down_revision = '28ccb38b118d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_close', sa.Float(), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('market_cap',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('pe_ratio',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('sector',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.alter_column('sector',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('pe_ratio',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('market_cap',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('previous_close')

    # ### end Alembic commands ###
